events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    
    server {
        # SSL/TLS設定 (ポート443のみ許可)
        listen 443 ssl;
        ssl_protocols TLSv1.2 TLSv1.3;
        
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # ルートディレクトリの設定
        root /var/www/html;
        index index.html;

        server_name login.42.fr;

        # テスト用に、アクセスしたら「Hello」とだけ返す設定
        location / {
            return 200 "Hello from NGINX!";
        }
    }
}